Added a static version of the wxWidgets crossbuild
GrandOrgue/WxWidgetsCross pull request #2
Opened 2024-02-27 09:55 UTC by larspalo

With this PR a static version of the wxWidgets library is also crosscompiled and available for usage.

2024-02-27 10:39 UTC, oleg68 requested changes

2024-02-27 10:39 UTC, oleg68 commented on build-scripts/for-win64/build-static-on-ubuntu.sh
> +Maintainer: Oleg Samarin <osamarin68@gmail.com>
Do you want to become an owner of wxwidgets3-mingw-w64-static?

2024-02-27 10:39 UTC, oleg68 commented on build-scripts/for-win64/build-static-on-ubuntu.sh
> +mkdir -p build/win64
```suggestion
mkdir -p build/win64-static
```

And everyewhere later.

Reason: if someone debugs both build types in a local environment, they should not conflict.

2024-02-27 12:37 UTC, larspalo commented on build-scripts/for-win64/build-static-on-ubuntu.sh
> +Maintainer: Oleg Samarin <osamarin68@gmail.com>
Sure I can change it if it's ok with you.

2024-02-27 12:37 UTC, larspalo commented on build-scripts/for-win64/build-static-on-ubuntu.sh
> +mkdir -p build/win64
Ok, I'll change that.

2024-02-27 15:04 UTC, larspalo commented on build-scripts/for-win64/build-static-on-ubuntu.sh
> +mkdir -p build/win64
@oleg68 In addition to your suggestions above, I also added some changes to get rid of the deprecated warnings when running the workflow file. It's the same type of changes that are already applied to the GO workflow file.

2024-02-28 06:48 UTC, oleg68 commented
@larspalo Do you have sufficient permissions for merging this PR by youself? Or I need to change the access rights?

2024-02-28 12:38 UTC, merged